apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: roboshop
    tier: db
spec:
  replicas: 1
  selector:
  # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: roboshop
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: arjunaws/mongodb:v1  # presented in my docker hub
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5

